// Флагман v1.0.5 — интеллектуальный выбор единицы + количество
var parsedItems=[], textReportGlobal='';
function setTheme(t){document.querySelectorAll('.theme-switch button').forEach(function(b){b.classList.remove('active')});var b=document.getElementById('theme-'+t);if(b)b.classList.add('active');localStorage.setItem('user-theme',t);document.documentElement.className=(t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))?'dark':'light'}
function clearAll(){inputText.value='';resultBox.style.display='none';parsedItems=[];textReportGlobal='';inputText.focus()}
function unitWord(s){s=(s||'').toLowerCase();if(/^(мм|mm|миллиметр\w*)$/.test(s))return'мм';if(/^(см|cm|сантиметр\w*)$/.test(s))return'см';if(/^(м|m|метр\w*|meter\w*)$/.test(s))return'м';return null}
function explicitUnit(line,a,b){var s=line.slice(b,b+30),m=s.match(/\b(мм|mm|миллиметр\w*|см|cm|сантиметр\w*|м|m|метр\w*|meter\w*)\b/i);if(m)return unitWord(m[1]);s=line.slice(Math.max(0,a-35),a);m=s.match(/\b(мм|mm|миллиметр\w*|см|cm|сантиметр\w*|м|m|метр\w*)\s*$/i);if(m)return unitWord(m[1]);m=line.match(/(?:размер\w*|габарит\w*|величин\w*)[^\n]{0,35}\b(мм|mm|миллиметр\w*|см|cm|сантиметр\w*|м|m|метр\w*|meter\w*)\b/i);return m?unitWord(m[1]):null}
function quantity(line,a,b){var s=line.slice(b,b+40),m=s.match(/^\s*[xх×*]\s*(\d+(?:\.\d+)?)\s*(?:шт\.?|штук|мест(?:а|о)?)?/i);if(m)return+ m[1];m=s.match(/^\s*(?:кол-?во|количество|мест)\s*[:\-]?\s*(\d+(?:\.\d+)?)/i);if(m)return+m[1];m=s.match(/^\s*(\d+(?:\.\d+)?)\s*(?:шт\.?|штук|мест(?:а|о)?)/i);if(m)return+m[1];s=line.slice(Math.max(0,a-25),a);m=s.match(/(\d+(?:\.\d+)?)\s*(?:шт\.?|штук|мест(?:а|о)?)\s*$/i);return m?+m[1]:1}
function vol(l,w,h,u,q){return l*w*h*q/(u==='м'?1:u==='см'?1e6:1e9)}
function score(l,w,h,u,q,line){var f=u==='м'?1:u==='см'?.01:.001,d=[l*f,w*f,h*f],mn=Math.min.apply(null,d),mx=Math.max.apply(null,d),md=d.slice().sort(function(a,b){return a-b})[1],v=vol(l,w,h,u,1),tv=v*q,s=0;if(mn>=.02&&mx<=20)s+=18;if(mn>=.05&&mx<=15)s+=12;if(md>=.15&&md<=3)s+=12;if(v>=.0005&&v<=80)s+=18;if(tv>=.001&&tv<=500)s+=15;if(tv>500)s-=35;if(tv<.000001)s-=30;if(u==='мм'&&Math.max(l,w,h)>=300&&Math.max(l,w,h)<=3000)s+=10;if(u==='см'&&Math.max(l,w,h)>=5&&Math.max(l,w,h)<=250)s+=8;if(u==='м'&&Math.max(l,w,h)>=1&&Math.max(l,w,h)<=15)s+=8;if(/груз|короб|паллет|упаков|мест|ящик|поддон|фура|перевоз|доставк|габарит|размер/i.test(line)&&v>=.001&&v<=80)s+=10;return s}
function choose(l,w,h,q,line,ex){if(ex)return{u:ex,d:false,msg:''};var a=['мм','см','м'].map(function(u){return{u:u,s:score(l,w,h,u,q,line)}}).sort(function(a,b){return b.s-a.s}),gap=a[0].s-a[1].s,d=gap<12;return{u:a[0].u,d:d,msg:d?'⚠️ Автовыбор: '+a[0].u+'. Возможен вариант '+a[1].u+'. Проверьте единицу измерения.':''}}
function calculate(){var raw=inputText.value;if(!raw.trim())return alert('Введите текст');var lines=raw.replace(/(\d+),(\d+)/g,'$1.$2').split('\n'),off=0,id=1;parsedItems=[];var re=/(\d+(?:\.\d+)?)\s*(?:x|х|×|\*)\s*(\d+(?:\.\d+)?)\s*(?:x|х|×|\*)\s*(\d+(?:\.\d+)?)/gi;lines.forEach(function(orig){var line=orig.toLowerCase().replace(/\d{2}\.\d{2}\.\d{4}/g,' ').replace(/\d+-[a-zа-я][a-zа-я0-9]*/gi,' ').replace(/\d+\/[a-zа-я][a-zа-я0-9]*/gi,' '),m,found=false;re.lastIndex=0;while((m=re.exec(line))){found=true;var l=+m[1],w=+m[2],h=+m[3],q=quantity(line,m.index,re.lastIndex),ex=explicitUnit(line,m.index,re.lastIndex),c=choose(l,w,h,q,line,ex);parsedItems.push({id:id++,start:off,end:off+orig.length,isValid:true,l:l,w:w,h:h,quantity:q,unit:c.u,isDoubtful:c.d,msg:c.msg})}if(!found){var n=line.match(/\d+(?:\.\d+)?/g);if(n&&n.length>=3){var l2=+n[0],w2=+n[1],h2=+n[2],q2=quantity(line,0,0),ex2=explicitUnit(line,0,line.length),c2=choose(l2,w2,h2,q2,line,ex2);parsedItems.push({id:id++,start:off,end:off+orig.length,isValid:true,l:l2,w:w2,h:h2,quantity:q2,unit:c2.u,isDoubtful:c2.d,msg:c2.msg})}}off+=orig.length+1});renderResults()}
function renderResults(){var total=0,pieces=0,warn=0,html='',rep='📊 ОТЧЕТ ПО РАСЧЕТУ ОБЪЕМА:\n\n';parsedItems.forEach(function(x,i){if(!x.isValid)return;if(x.isDoubtful)warn++;var v=vol(x.l,x.w,x.h,x.unit,x.quantity);total+=v;pieces+=x.quantity;html+='<div class="detail-line '+(x.isDoubtful?'warning-line':'')+'">Позиция '+x.id+': '+x.l+'x'+x.w+'x'+x.h+' <div class="badge-group"><button class="btn-badge '+(x.unit==='м'?'active':'')+'" data-i="'+i+'" data-unit="м">м</button><button class="btn-badge '+(x.unit==='см'?'active':'')+'" data-i="'+i+'" data-unit="см">см</button><button class="btn-badge '+(x.unit==='мм'?'active':'')+'" data-i="'+i+'" data-unit="мм">мм</button></div> × '+x.quantity+' шт. = <strong>'+v.toFixed(4)+'</strong> м³'+(x.isDoubtful?'<div class="warning-text">'+x.msg+'</div>':'')+'</div>';rep+='• Позиция '+x.id+': '+x.l+'x'+x.w+'x'+x.h+' '+x.unit+' × '+x.quantity+' шт. = '+v.toFixed(4)+' м³\n'});if(!parsedItems.length)document.getElementById('detailsList').innerHTML='';calcStatus.className='calc-status '+(warn?'warn':'ok');calcStatus.innerHTML=warn?'🟡 Расчёт требует проверки<br><small>'+warn+' позиция требует проверки единицы.</small>':'🟢 Расчёт завершён<br><small>Все позиции распознаны без предупреждений.</small>';totalVolume.innerHTML='<strong>'+total.toFixed(4)+'</strong> м³';totalPieces.innerText=pieces+' шт.';detailsList.innerHTML=html;resultBox.style.display='block';textReportGlobal=rep+'\n🚚 ОБЩИЙ ОБЪЕМ: '+total.toFixed(4)+' м³\n🔢 ВСЕГО МЕСТ: '+pieces+' шт.'}
document.addEventListener('DOMContentLoaded',function(){setTheme(localStorage.getItem('user-theme')||'system');theme-light.onclick=function(){setTheme('light')};theme-dark.onclick=function(){setTheme('dark')};theme-system.onclick=function(){setTheme('system')};calcBtn.onclick=calculate;clearBtn.onclick=clearAll;copyBtn.onclick=function(){navigator.clipboard.writeText(textReportGlobal)};detailsList.onclick=function(e){var b=e.target.closest('.btn-badge');if(!b)return;var x=parsedItems[+b.dataset.i];x.unit=b.dataset.unit;x.isDoubtful=false;x.msg='';renderResults()};inputText.addEventListener('paste',function(){setTimeout(calculate,50)})});
